---
services: docker

env:
  - distro=centos6
    version=latest
    init=/sbin/init
    volume=":"

  - distro=centos7
    init=/usr/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    version=latest
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=centos8
    init=/usr/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    version=latest
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=oracle6
    version=latest
    init=/sbin/init
    volume=":"

#  - distro=oracle7
#    init=/usr/lib/systemd/systemd
#    run_opts="--cap-add SYS_ADMIN"
#    version=latest

  - distro=ubuntu1604
    version=latest
    init=/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=ubuntu1804
    version=latest
    init=/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=debian9
    version=latest
    init=/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=debian10
    version=latest
    init=/lib/systemd/systemd
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=amazon
    init=/lib/systemd/systemd
    version=latest
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=fedora
    init=/lib/systemd/systemd
    version=latest
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - distro=arch
    init=/lib/systemd/systemd
    version=latest
    run_opts="--cap-add SYS_ADMIN"
    volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  # Pull container
  - 'docker pull rndmh3ro/docker-${distro}-ansible:${version}'

script:
  - pip install --user ansible-lint
  - ansible-lint ./

  - container_id=$(mktemp)
  # Run container in detached state.
  - 'docker run --detach --volume="${volume}" --volume="${PWD}":/etc/ansible/roles/ansible-ssh-hardening:ro ${run_opts} rndmh3ro/docker-${distro}-ansible:${version} "${init}" > "${container_id}"'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-ssh-hardening/tests/default_custom.yml --diff'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/ansible-ssh-hardening/tests/default.yml --diff'

  # Verify role
  - 'inspec exec https://github.com/dev-sec/ssh-baseline/ -t docker://$(cat ${container_id}) --no-distinct-exit'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
